/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { MatherAnalytics } from 'react-native-mather-analytics';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    const matherAnalytics = new MatherAnalytics('ma01278', '96248264');
    console.log('Firing trackPageView');
    matherAnalytics.trackPageView({
      pageUrl: 'http://www.mynewspaper.com',
      pageTitle: 'Time for Sports',
      referrer: 'http://www.anothernewspaper.com',
      userId: {
        user: 'doug@mynewspaper.com',
        loggedIn: true,
      },
      section: 'sports',
      author: 'by author one and author two',
      pageType: 'article',
      articlePublishTime: {
        time: '2016-05-05T15:41:38',
        timeZone: 'America/Los_Angeles',
        format: "yyyy-MM-dd'T'HH:mm:ss",
      },
      premium: true,
      metered: '1|5',
      publication: 'The Reader News',
      categories: [
        'structure',
        'structure/home_page',
        'columbus',
        'ohio',
        'new',
        'sports',
      ],
      appName: 'Best News Reader',
      referenceNav: 'SectionScroll',
      articleId: '3245671.b',
      articleUpdateTime: {
        time: '2016-05-06T16:41:38',
        timeZone: 'America/Los_Angeles',
        format: "yyyy-MM-dd'T'HH:mm:ss",
      },
      hierarchy: [
        'sports',
        'local',
        'highschool',
      ],
      email: 'kurt@gmail.com',
      articleSource: 'AP',
      mediaType: 'video',
      articleType: 'editorial',
      characterCount: '25000',
      wordCount: '1200',
      paragraphCount: '33',
      scrollPercent: '50',
      pageNumber: 'A5',
      addCtxSection: {
        name: 'identities',
        value: {
          'type': 'paywallUserId',
          'id': 'paywallUserId',
        },
      },
      userDB: {
        minPageViews: 2,
        timeoutMs: 10000,
        noCache: false,
        userDBUr: 'https://app.matheranalytics.com',
      },
    });

    console.log('Firing trackAction');
    matherAnalytics.trackAction({
      type: 'paywall',
      category: 'block',
      action: 'stop',
      custom: {
        name: 'vendor',
        value: 'custom',
      },
    });

    console.log('Firing trackImpression');
    matherAnalytics.trackImpression({
      eaid: '263509965',
      ebuy: '380850765',
      eadv: '83331405',
      ecid: '97302828285',
      epid: '101145405',
      esid: '100998765',
      custom: {
        name: 'server',
        value: 'adx',
      },
    });
  }
  render() {
    return (
        <View style={styles.container}>
          <Text style={styles.welcome}>☆MatherAnalytics example☆</Text>
          <Text style={styles.instructions}>Firing trackPageView, trackAction and trackImpression</Text>
        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
